fix: update chrome extension link
zenorocha/clipboard.js pull request #786
Opened 2021-12-22 02:10 UTC by wangmeijian

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `dev` branch for v2.x (or to a previous version branch), _not_ the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

2022-01-27 09:36 UTC, helderburato commented
Hi @wangmeijian, thanks for contributing to the project. 

I was checking and the extension you updated the link isn't the expected for this package, we need to check why the correct isn't available on the Chrome Extensions.

could you check this? @zenorocha

2022-01-31 14:05 UTC, oaraujocesar approved these changes

2022-01-31 14:07 UTC, helderburato requested changes
It needs to be checked.

2022-02-03 18:30 UTC, helderburato commented
I'll open an issue to keep tracking of this item, but I'll close this PR considering this link won't be used. 

Thanks for your contribution @wangmeijian.

2022-02-03 18:31 UTC, closed without merging